services:
  # proxy:
  #   container_name: proxy
  #   image: nginx:1.29
  #   restart: unless-stopped
  #   cap_add:
  #     - NET_BIND_SERVICE
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/conf.d:/etc/nginx/conf.d:ro
  #       # - ./nginx/ssl:/etc/nginx/ssl:ro
  #   ports:
  #     # DNS
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     # WEB
  #     - "80:80/tcp"
  #     - "443:443/tcp"
  #     # DB
  #     - "3306:3306/tcp"

  # dns:
  #   container_name: dns
  #   build:
  #     context: dns/
  #   restart: unless-stopped
  #   dns: 127.0.0.1
  #   volumes:
  #     - ./dns/config:/etc/bind/

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:18.8.9-ce.0
    restart: unless-stopped
    hostname: 'gitlab.krem.lan'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.krem.lan'

        # Monitoring
        prometheus_monitoring['enable'] = false
        prometheus['enable'] = false
        alertmanager['enable'] = false
        node_exporter['enable'] = false
        redis_exporter['enable'] = false
        postgres_exporter['enable'] = false
        gitlab_exporter['enable'] = false

        # Puma Web Server
        # Setting workers to 0 runs Puma in single mode.
        puma['worker_processes'] = 0
        puma['min_threads'] = 1
        puma['max_threads'] = 4

        # Sidekiq Background Jobs
        sidekiq['max_concurrency'] = 10

        # PostgreSQL
        postgresql['shared_buffers'] = "256MB"

        # Gitlab OCI
        registry_external_url 'https://gitlab.krem.lan:5050'

    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - "gitlab-config:/etc/gitlab"
      - "gitlab-logs:/var/log/gitlab"
      - "gitlab-data:/var/opt/gitlab"
    shm_size: "256m"

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
