services:
  proxy:
    container_name: proxy
    image: nginx:1.29
    restart: unless-stopped
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      # configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/stream.conf.d/:/etc/nginx/stream.conf.d/
      # certificates
      - /etc/ssl/certs/krem.lan.crt:/etc/ssl/certs/krem.lan.crt
      - /etc/ssl/private/krem.lan.key:/etc/ssl/private/krem.lan.key
    ports:
      # DNS
      - "53:53/tcp"
      - "53:53/udp"
      # WEB
      - "80:80/tcp"
      - "443:443/tcp"
      # DB
      - "3306:3306/tcp"
    networks:
      homelab-net:
        ipv4_address: 172.30.0.10

  dns:
    container_name: dns
    build:
      context: dns/
    restart: unless-stopped
    dns: 127.0.0.1
    volumes:
      - ./dns/config:/etc/bind/
    # ports:
    #   - '53:53/udp'
    networks:
      homelab-net:
        ipv4_address: 172.30.0.11

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:18.8.9-ce.0
    restart: unless-stopped
    hostname: 'gitlab.krem.lan'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://gitlab.krem.lan"
        registry_external_url "https://oci.krem.lan"

        # NGINX config (embedded)
        # edge ssl
        nginx['listen_port'] = 80
        nginx['listen_https'] = false

        # same for registry
        registry_nginx['listen_port'] = 5500
        registry_nginx['listen_https'] = false

        # trust the headers from nginx
        nginx['real_ip_trusted_addresses'] = ["172.30.0.10", "10.0.0.0/8"]

        # Monitoring
        prometheus_monitoring['enable'] = false
        prometheus['enable'] = false
        alertmanager['enable'] = false
        node_exporter['enable'] = false
        redis_exporter['enable'] = false
        postgres_exporter['enable'] = false
        gitlab_exporter['enable'] = false

        # Puma Web Server
        # Setting workers to 0 runs Puma in single mode.
        puma['worker_processes'] = 0
        puma['min_threads'] = 1
        puma['max_threads'] = 4

        # Sidekiq Background Jobs
        sidekiq['max_concurrency'] = 10

        # PostgreSQL
        postgresql['shared_buffers'] = "256MB"

    # ports:
      # - "80:80"
      # - "22:22"
    volumes:
      - "gitlab-config:/etc/gitlab"
      - "gitlab-logs:/var/log/gitlab"
      - "gitlab-data:/var/opt/gitlab"
    shm_size: "256m"
    networks:
      homelab-net:
        ipv4_address: 172.30.0.12

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

networks:
  homelab-net:
    ipam:
      config:
        - subnet: 172.30.0.0/24
