# /etc/nginx/nginx.conf

# ==============================
# 1. MAIN BLOCK
# ==============================

user nginx;

# Enable multiples workers per core
worker_processes auto;

# Centralized error logging. 'warn' is a sensible production baseline—it keeps
# disk I/O low by ignoring trivial info but captures actionable degradation metrics.
error_log /var/log/nginx/error.log warn;

# pid file enables sending signals to the main NGINX process
pid /var/run/nginx.pid;

worker_rlimit_nofile 32768;


# ==============================
# 2. EVENTS BLOCK
# ==============================
events {
    # max number of simultaneous connections a worker can hold open
    worker_connections 16384;

	# accept all connections at once
    multi_accept on;
}


# ==============================
# 3. HTTP BLOCK
# ==============================
http {
    # --- Core Settings ---
    # Maps file extensions to MIME types so browsers know how to render the data.
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # do not emit the NGINX version number in error pages
    server_tokens off;

	# use the sendfile() syscall to copy from cache to network socket directly
    sendfile on;

	# do not reserve a full TCP paquet for only http headers
    tcp_nopush on;

    # NGINX will push data immediately regardless of packet size
    tcp_nodelay on;

    # drop connections from clients that are idle for too long
    keepalive_timeout 65;

# --- Observability & Logging ---
    log_format json_combined escape=json 
    '{'
        '"time": "$time_iso8601",'
        '"client_ip": "$remote_addr",'
        '"request_method": "$request_method",'
        '"request_uri": "$request_uri",'
        '"server_protocol": "$server_protocol",'
        '"status": "$status",'
        '"body_bytes_sent": "$body_bytes_sent",'
        '"request_time": "$request_time",'
        '"upstream_response_time": "$upstream_response_time",'
        '"upstream_addr": "$upstream_addr",'
        '"http_referer": "$http_referer",'
        '"http_user_agent": "$http_user_agent",'
        '"http_x_forwarded_for": "$http_x_forwarded_for"'
    '}';

    access_log /var/log/nginx/access.log json_combined;

    include /etc/nginx/conf.d/*.conf;
}

# ==============================
# 4. STREAM BLOCK 
# ==============================
stream {
    # --- Observability ---
    log_format stream_json escape=json
    '{'
        '"time": "$time_iso8601",'
        '"client_ip": "$remote_addr",'
        '"protocol": "$protocol",'
        '"status": "$status",'
        '"bytes_sent": "$bytes_sent",'
        '"bytes_received": "$bytes_received",'
        '"session_time": "$session_time",'
        '"upstream_addr": "$upstream_addr",'
    '}';

    # Log to a separate file so HTTP and Stream logs don't intermingle.
    access_log /var/log/nginx/stream-access.log stream_json;

    # max time to establish a TCP handshake with the backend
    proxy_connect_timeout 3s;

	# allow long databases connections
    proxy_timeout 30m;

    include /etc/nginx/stream.conf.d/*.conf;
}
