# ==============================
# GITLAB OCI REGISTRY ROUTING
# ==============================

upstream registry_backend {
    server gitlab:5500;
}

server {
    listen 80;
    server_name oci.krem.lan;

	# location /.well-known/acme-challenge/ {
    #     root /var/www/certbot;
    # }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name oci.krem.lan;

    # SSL/TLS Configuration
    ssl_certificate     /etc/ssl/certs/krem.lan.crt;
    ssl_certificate_key /etc/ssl/private/krem.lan.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # OCI Registry Specific Tweaks
    client_max_body_size 0;
    chunked_transfer_encoding on;

    # Disable buffering for heavy image layers
    proxy_buffering off;
    proxy_request_buffering off;

    location / {
        # Docker Daemon Reverse Proxy Headers
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_pass http://registry_backend;
    }
}
