# ===============================
# MARIADB
# ===============================

upstream mariadb_backend {
    server 172.30.0.20:3306; 
}

server {
    listen 3306;

    allow 10.10.0.0/24;
    deny all;

    proxy_timeout 15m;

    proxy_pass mariadb_backend;
}
