# ===============================
# MARIADB
# ===============================

upstream mariadb_backend {
    server db:3306; 
}

server {
    listen 3306;

    allow 10.10.0.0/24;
    deny all;

    proxy_timeout 15m;

    so_keepalive=on;

    proxy_pass mariadb_backend;
}
