# ==============================
# BIND DNS
# ==============================

upstream dns_backend {
    server 172.30.0.11:53; # dns service ip
}

server {
    listen 53 udp;

	# free memory after 1 response
    proxy_responses 1;

	# short timeout
    proxy_timeout 10s;

    proxy_pass dns_backend;
}
